In [3]:
import pandas as pd
import numpy as np

In [25]:
np.linspace(200,1400,4)

array([ 200.,  600., 1000., 1400.])

In [4]:
df = pd.read_csv('data/3.csv') #first rows are name of variables so it is automatically read as objects
#df.columns =df.iloc[0] #.reset_index(drop = True)
#df.drop(index=df.index[0], axis=0, inplace=True)

In [7]:
nocatch = df[df["catch"]==0] 
nocatch.reset_index(inplace = True, drop=True)

In [10]:
df_v = nocatch[nocatch['modality'] == "visual"]
df_a = nocatch[nocatch['modality'] == "auditory"]

In [11]:
df_v.groupby(['v_pred','v_leading','v_trailing', "resp"]).size().reset_index().rename(columns={0:'count'})

Empty DataFrame
Columns: [v_pred, v_leading, v_trailing, resp, count]
Index: []

In [15]:
df_a.groupby(['block', 'a_pred','a_leading','a_trailing', "resp"]).size().reset_index().rename(columns={0:'count'})

    block a_pred  a_leading  a_trailing        resp  count
0       0    EXP      200.0       467.0    familiar      2
1       0    EXP      200.0       467.0  unfamiliar      2
2       0    EXP      467.0      1000.0    familiar      4
3       0    EXP      467.0      1000.0  unfamiliar      1
4       0    EXP     1000.0       200.0    familiar      4
5       0    EXP     1000.0       200.0  unfamiliar      2
6       0      N      733.0       200.0    familiar      1
7       0      N      733.0       200.0  unfamiliar      1
8       0      N      733.0       467.0  unfamiliar      2
9       0      N      733.0      1000.0  unfamiliar      2
10      0     VP      200.0       200.0  unfamiliar      1
11      0     VP      200.0      1000.0    familiar      1
12      0     VP      467.0       200.0  unfamiliar      1
13      0     VP      467.0       467.0  unfamiliar      1
14      0     VP     1000.0       467.0  unfamiliar      1
15      0     VP     1000.0      1000.0  unfamiliar      1
16      1    EXP      200.0       467.0    familiar      1
17      1    EXP      200.0       467.0  unfamiliar      3
18      1    EXP      467.0      1000.0    familiar      4
19      1    EXP      467.0      1000.0  unfamiliar      1
20      1    EXP     1000.0       200.0    familiar      6
21      1      N      733.0       200.0  unfamiliar      2
22      1      N      733.0       467.0  unfamiliar      2
23      1      N      733.0      1000.0    familiar      2
24      1     VP      200.0       200.0  unfamiliar      1
25      1     VP      200.0      1000.0  unfamiliar      1
26      1     VP      467.0       200.0  unfamiliar      1
27      1     VP      467.0       467.0  unfamiliar      1
28      1     VP     1000.0       467.0  unfamiliar      1
29      1     VP     1000.0      1000.0  unfamiliar      1
30      2    EXP      200.0       467.0    familiar      4
31      2    EXP      467.0      1000.0    familiar      3
32      2    EXP      467.0      1000.0  unfamiliar      2
33      2    EXP     1000.0       200.0    familiar      6
34      2      N      733.0       200.0  unfamiliar      2
35      2      N      733.0       467.0    familiar      1
36      2      N      733.0       467.0  unfamiliar      1
37      2      N      733.0      1000.0  unfamiliar      2
38      2     VP      200.0       200.0  unfamiliar      1
39      2     VP      200.0      1000.0  unfamiliar      1
40      2     VP      467.0       200.0  unfamiliar      1
41      2     VP      467.0       467.0  unfamiliar      1
42      2     VP     1000.0       467.0  unfamiliar      1
43      2     VP     1000.0      1000.0  unfamiliar      1
44      3    EXP      200.0       467.0    familiar      3
45      3    EXP      200.0       467.0  unfamiliar      1
46      3    EXP      467.0      1000.0  unfamiliar      5
47      3    EXP     1000.0       200.0    familiar      6
48      3      N      733.0       200.0  unfamiliar      2
49      3      N      733.0       467.0  unfamiliar      2
50      3      N      733.0      1000.0    familiar      2
51      3     VP      200.0       200.0  unfamiliar      1
52      3     VP      200.0      1000.0  unfamiliar      1
53      3     VP      467.0       200.0  unfamiliar      1
54      3     VP      467.0       467.0  unfamiliar      1
55      3     VP     1000.0       467.0  unfamiliar      1
56      3     VP     1000.0      1000.0  unfamiliar      1

In [19]:
df_a.groupby(['a_leading','a_trailing']).size().reset_index().rename(columns={0:'count'})

    a_leading  a_trailing  count
0       200.0       200.0      4
1       200.0       467.0     16
2       200.0      1000.0      4
3       467.0       200.0      4
4       467.0       467.0      4
5       467.0      1000.0     20
6       733.0       200.0      8
7       733.0       467.0      8
8       733.0      1000.0      8
9      1000.0       200.0     24
10     1000.0       467.0      4
11     1000.0      1000.0      4

In [6]:
nocatch = df[df["catch"] == 0]
nocatch.reset_index(drop=True, inplace=True)

In [17]:
def accuracyV(df):
    hits = len(df[(df["v_pred"] == "EXP") & (df["resp"] == "familiar")]) + len(df[(df["v_pred"] == "VP") & (df["resp"] == "unfamiliar")])
    misses = len(df[(df["v_pred"] == "EXP") & (df["resp"] != "familiar")]) + len(df[(df["v_pred"] == "VP") & (df["resp"] != "familiar")])
    
    acc = (hits/(hits+misses)) *100
    
    return acc

def accuracyA(df):
    hits = len(df[(df["a_pred"] == "EXP") & (df["resp"] == "familiar")]) + len(df[(df["a_pred"] == "VP") & (df["resp"] == "unfamiliar")])
    misses = len(df[(df["a_pred"] == "EXP") & (df["resp"] != "familiar")]) + len(df[(df["a_pred"] == "VP") & (df["resp"] != "familiar")])
    
    acc = (hits/(hits+misses)) *100
    
    return acc

In [54]:
nocatchv = nocatch[nocatch['modality']=="visual"]
nocatcha = nocatch[nocatch['modality']=="auditory"]
nocatchv.reset_index(drop=True, inplace=True)
nocatcha.reset_index(drop=True, inplace=True)

In [18]:
accuracyA(df_a)

62.264150943396224

In [6]:
180/70

2.5714285714285716

In [7]:
180/7

25.714285714285715

In [8]:
160/7

22.857142857142858

In [12]:
def block_accuracy(df, modality):
    if modality == "visual":
        hits = len(df[(df.iloc[:,8] == "EXP") & (df.iloc[:,15] == "familiar")]) + \
               len(df[(df.iloc[:,8] == "VP") & (df.iloc[:,15] == "unfamiliar")]) + \
               len(df[(df.iloc[:,8] == "N") & (df.iloc[:,15] == "unfamiliar")]) + \
               len(df[(df.iloc[:,8] == 1) & (df.iloc[:,15] == "catch")])
    else:
        hits = len(df[(df.iloc[:,11] == "EXP") & (df.iloc[:,15] == "familiar")]) + \
               len(df[(df.iloc[:,11] == "VP") & (df.iloc[:,15] == "unfamiliar")]) + \
               len(df[(df.iloc[:,11] == "N") & (df.iloc[:,15] == "unfamiliar")]) + \
               len(df[(df.iloc[:,11] == 1) & (df.iloc[:,15] == "catch")])
                  
    accuracy = str(round(((hits / len(df)) * 100), 2))    
    return accuracy

In [13]:
for block in [0,2,4,6]:
    accuracy = block_accuracy(df[df["block"]==block], "auditory")
    print(accuracy)

41.67
47.22
47.22
44.44

In [11]:
block_accuracy(df[df["block"]==block], "auditory")

In [14]:
for block in [1,3,5,7]:
    accuracy = block_accuracy(df[df["block"]==block], "visual")
    print(accuracy)

47.22
44.44
44.44
47.22

In [1]:
778/20

38.9